"""Trading universe: the PSX names the bot trades.

AUTO-GENERATED by scripts/select_universe.py on 2026-04-24,
hand-extended on 2026-04-28 to include NPL (user request).
  - 7 tickers user-required (REQUIRED_TICKERS in config/candidates.py)
  - 9 tickers selected by training-AUC ranking from the candidate pool

Edit config/candidates.py (REQUIRED_TICKERS or CANDIDATE_POOL) and re-run
the selector to regenerate this file. Any manual edits will be overwritten.
"""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class UniverseEntry:
    symbol: str
    name: str
    sector: str
    notes: str = ""


UNIVERSE: list[UniverseEntry] = [
    UniverseEntry("HUBC", "Hub Power", "Power",
                   "[user-required]"),
    UniverseEntry("PABC", "Pakistan Aluminium Beverage Cans", "Misc",
                   "[user-required]"),
    UniverseEntry("MLCF", "Maple Leaf Cement", "Cement",
                   "[user-required]"),
    UniverseEntry("OGDC", "Oil & Gas Development Co.", "Oil & Gas E&P",
                   "[user-required]"),
    UniverseEntry("FABL", "Faysal Bank", "Banking",
                   "[user-required]"),
    UniverseEntry("PPL", "Pakistan Petroleum", "Oil & Gas E&P",
                   "[user-required]"),
    UniverseEntry("NPL", "Nishat Power", "Power",
                   "[user-required]"),
    UniverseEntry("POL", "Pakistan Oilfields", "Oil & Gas E&P",
                   "[picked by selector, AUC=0.64]"),
    UniverseEntry("FCCL", "Fauji Cement", "Cement",
                   "[picked by selector, AUC=0.62]"),
    UniverseEntry("APL", "Attock Petroleum", "OMC/Refining",
                   "[picked by selector, AUC=0.61]"),
    UniverseEntry("EPCL", "Engro Polymer", "Conglomerate/Chem",
                   "[picked by selector, AUC=0.61]"),
    UniverseEntry("KOHC", "Kohat Cement", "Cement",
                   "[picked by selector, AUC=0.60]"),
    UniverseEntry("SEARL", "The Searle Company", "Pharma",
                   "[picked by selector, AUC=0.59]"),
    UniverseEntry("MCB", "MCB Bank", "Banking",
                   "[picked by selector, AUC=0.57]"),
    UniverseEntry("MEBL", "Meezan Bank", "Banking",
                   "[picked by selector, AUC=0.55]"),
    UniverseEntry("PSO", "Pakistan State Oil", "OMC/Refining",
                   "[picked by selector, AUC=0.54]"),
]


def symbols() -> list[str]:
    return [u.symbol for u in UNIVERSE]


def sector_of(symbol: str) -> str | None:
    for u in UNIVERSE:
        if u.symbol == symbol:
            return u.sector
    return None


def by_sector() -> dict[str, list[str]]:
    out: dict[str, list[str]] = {}
    for u in UNIVERSE:
        out.setdefault(u.sector, []).append(u.symbol)
    return out
